// Personal Information
export type UserType = 'rider' | 'driver';

export interface User {
  id?: string; // Optional, as it may be generated by the backend
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  userType: UserType;
  password?: string; // Optional, for registration purposes
  profilePicture?: string; // URL or base64 string
  // Driver-specific fields
}

// License Information
export interface LicenseInfo {
  licenseNumber: string;
  expirationDate: string;
  state: string;
}

// Vehicle Information
export interface VehicleInfo {
  make: string;
  model: string;
  year: string; 
  color: string;
  licensePlate: string;
}

// Document Upload Status
export interface Documents {
  license: 'uploaded' | 'pending' | 'missing';
  insurance: 'uploaded' | 'pending' | 'missing';
  registration: 'uploaded' | 'pending' | 'missing';
}

// Full Driver Registration Form
export interface DriverRegistrationForm {
  personalInfo: User;
  licenseInfo: LicenseInfo;
  vehicleInfo: VehicleInfo;
  documents: Documents;
}
